### DISCUSSION TITLE
Proposal: Adding ESP32_SUBCLASS_PROJECT_TEMPLATE option

### DISCUSSION THREAD

**Discussion by linfan68** [Moddable-OpenSource/moddable#1321] [Ideas]
I'm running into an situation where I need to include some native esp32 components into my project (the iot_usbh_modem component from esp-iot-solution)

The easy way to do this is to adding a file called "idf_component.yml" as follow:
```
dependencies:
  iot_usbh_modem:
    path: /workspaces/dk-hwjs/esp-iot-solution/components/usb/iot_usbh_modem
  # Notice I'm using a local copy of the component, normally it should be simplier like this:
  # component2:
  #   version: ">=2.0.0"
```
However, this requires updating the "Native" esp32 project, which is here:
$MODDABLE/build/devices/esp32/xsProj-esp32s3

Currently there is no good way to switch to a different "flavor" of the project template, this is hard-coded in:
`$MODDABLE/tools/mcconfig/make.esp32.mk`
```
PROJ_DIR_TEMPLATE = $(BUILD_DIR)/devices/esp32/xsProj-$(ESP32_SUBCLASS)
```

Here I'm proposing adding an optional build variable called ESP32_SUBCLASS_PROJECT_TEMPLATE, and change the code above into:

```
# if ESP32_SUBCLASS_PROJECT_TEMPLATE not defined, set it to ESP32_SUBCLASS
ESP32_SUBCLASS_PROJECT_TEMPLATE ?= $(ESP32_SUBCLASS)

PROJ_DIR_TEMPLATE = $(BUILD_DIR)/devices/esp32/xsProj-$(ESP32_SUBCLASS_PROJECT_TEMPLATE)

```

By doing this, simply adding this into the manifest file:
```
{
  "build": {
    "ESP32_SUBCLASS_PROJECT_TEMPLATE": "esp32s3_usb_modem"
  }
}
```

makes the template project switching possible.

This solves some problems but not all. In my case, I also need add idf_component.yml into the "copy file list" to make the make file copy this file, changes needed are (in make.esp32.mk file)
```
PROJ_DIR_TEMPLATE = $(BUILD_DIR)/devices/esp32/xsProj-$(ESP32_SUBCLASS_PROJECT_TEMPLATE)
PROJ_DIR_FILES = \
	$(PROJ_DIR)/main/main.c \
	$(PROJ_DIR)/main/component.mk \
	$(PROJ_DIR)/main/idf_component.yml \  # <<<< this line
	$(PROJ_DIR)/main/CMakeLists.txt \
	$(PROJ_DIR)/CMakeLists.txt \
	$(PROJ_DIR)/partitions.csv \
	$(PROJ_DIR)/Makefile

# 
#  and this
# 
$(PROJ_DIR)/main/idf_component.yml: $(PROJ_DIR)/main $(PROJ_DIR_TEMPLATE)/main/idf_component.yml
	cp -f $(PROJ_DIR_TEMPLATE)/main/idf_component.yml $@
```
